# Generated by Django 4.1.7 on 2023-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Introduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=800)),
                ("image", models.ImageField(upload_to="peoplez/")),
            ],
        ),
        migrations.CreateModel(
            name="StoryTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=2500)),
                ("image1", models.ImageField(upload_to="peoplez/")),
                ("image2", models.ImageField(upload_to="peoplez/")),
                ("image3", models.ImageField(upload_to="peoplez/")),
            ],
        ),
    ]
